language: node_js
node_js:
  - "node"
  - "lts/*"
  - "10"
  - "8"
  - "6"
script:
  - yarn
  - yarn tslint
  - yarn build
  - yarn test
  - yarn test:js
  - yarn test:ts
  - yarn test:coveralls
cache:
  yarn: true
  directories:
    - "node_modules"