language: node_js
node_js:
  - node
  - "6"
  - "4"
script:
  - yarn
  - yarn tslint
  - yarn test:coveralls
  - yarn build
  - yarn test
  - yarn test:js
  - yarn test:ts
cache:
  yarn: true
  directories:
    - "node_modules"